const maps = {
	"legends": {
		"A": "horizontal bridge/stairs",
		"B": "vertical bridge/stairs",
		"C": "castle",
		"D": "dried water",
		"E": "cliff edge",
		"F": "forest",
		"G": "grass",
		"L": "lake",
		"M": "mountain",
		"N": "big mountain",
		"P": "plains",
		"R": "road",
		"S": "sand",
		"T": "burned tree",
		"V": "volcan",
		"W": "water",
		"X": "water fall",
		"Y": "weeds"
	},
	"mouvement" : [1,1,3,0,2,2,2,0,1,2,1,2,0,0],
	"coordinate": {
		"A": {"x": 110, "y": 88, "w": 16, "h":16},
		"B": {"x": 78, "y": 88, "w": 16, "h":16},
		"C": {"x": 86, "y": 185, "w": 48, "h":32},
		"D": {"x": 14, "y": 56, "w": 16, "h":16},
		"E": {"x": 14, "y": 56, "w": 16, "h":16},
		"F": {"x": 14, "y": 185, "w": 16, "h":16},
		"G": {"x": 78, "y": 56, "w": 16, "h":16},
		"L": {"x": 14, "y": 56, "w": 16, "h":16},
		"M": {"x": 46, "y": 88, "w": 16, "h":16},
		"N": {"x": 142, "y": 56, "w": 32, "h":32},
		"P": {"x": 14, "y": 56, "w": 16, "h":16},
		"R": {"x": 46, "y": 56, "w": 16, "h":16},
		"S": {"x": 14, "y": 56, "w": 16, "h":16},
		"T": {"x": 14, "y": 56, "w": 16, "h":16},
		"V": {"x": 14, "y": 56, "w": 16, "h":16},
		"W": {"x": 14, "y": 353, "w": 16, "h":16},
		"X": {"x": 14, "y": 56, "w": 16, "h":16},
		"Y": {"x": 14, "y": 56, "w": 16, "h":16}
	},
	"charactersPlace": [
		[
			[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
			[null, "C", "C", "C", null, null, null, null, null, null, null, null, null, null, null, null, "Z", "Z", "Z", null],
			[null, "C", "C", "C", null, null, null, null, null, null, null, null, null, null, null, null, "Z", "Z", "Z", null],
			[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]
		],
	],
	"rounds": [
		[
			["W", "W", "W", "W", "W", "W", "W", "W", "W", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P"],
			["W", "W", "W", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "F"],
			["W", "P", "P", "P", "P", "P", "P", "R", "R", "R", "R", "R", "R", "R", "P", "P", "F", "F", "F", "F"],
			["W", "C", "C", "C", "P", "P", "P", "R", "F", "P", "P", "P", "P", "R", "P", "P", "Z", "Z", "Z", "F"],
			["W", "C", "C", "C", "P", "P", "P", "R", "P", "P", "P", "P", "P", "R", "P", "P", "Z", "Z", "Z", "R"],
			["W", "P", "R", "P", "F", "P", "P", "R", "P", "P", "P", "P", "P", "R", "P", "P", "F", "R", "F", "F"],
			["W", "P", "R", "R", "F", "P", "P", "R", "P", "P", "G", "G", "P", "R", "P", "P", "P", "R", "F", "P"],
			["W", "W", "P", "R", "R", "R", "R", "R", "P", "G", "G", "G", "G", "R", "R", "R", "R", "R", "P", "P"],
			["W", "W", "W", "W", "W", "P", "P", "P", "G", "G", "M", "M", "G", "P", "P", "P", "P", "G", "G", "P"]
		],
		[
			["P", "P", "P", "P", "P", "F", "F", "M", "M", "F", "F", "M", "F", "F", "F", "F", "F", "W", "W", "W"],
			["P", "P", "P", "P", "F", "R", "R", "R", "R", "R", "R", "R", "R", "R", "F", "P", "P", "P", "W", "W"],
			["P", "F", "F", "F", "F", "R", "P", "P", "P", "P", "P", "P", "P", "R", "R", "P", "P", "P", "P", "W"],
			["P", "C", "C", "C", "F", "R", "P", "P", "P", "P", "P", "P", "P", "P", "R", "P", "F", "P", "P", "P"],
			["P", "C", "C", "C", "R", "R", "P", "P", "F", "F", "P", "P", "P", "P", "R", "P", "Z", "Z", "Z", "P"],
			["P", "P", "R", "F", "F", "R", "P", "P", "P", "P", "P", "P", "P", "P", "R", "P", "Z", "Z", "Z", "P"],
			["P", "P", "R", "F", "P", "R", "R", "R", "P", "P", "P", "P", "P", "G", "R", "P", "P", "R", "P", "P"],
			["R", "R", "R", "P", "P", "P", "P", "R", "R", "R", "R", "R", "R", "R", "R", "P", "P", "R", "P", "P"],
			["P", "P", "G", "G", "P", "P", "P", "F", "F", "M", "M", "F", "F", "F", "R", "R", "R", "R", "F", "P"]
		],
		[
			["P", "F", "P", "P", "P", "W", "W", "W", "W", "W"],
			["P", "C", "C", "C", "P", "P", "W", "W", "W", "W"],
			["P", "C", "C", "C", "P", "P", "G", "W", "W", "W"],
			["P", "P", "R", "P", "P", "S", "S", "G", "W", "W"],
			["P", "P", "R", "P", "P", "S", "S", "G", "W", "W"],
			["R", "R", "R", "F", "P", "S", "S", "G", "P", "P"],
			["P", "P", "R", "R", "R", "R", "F", "P", "P", "P"],
			["P", "P", "W", "W", "W", "R", "R", "F", "P", "P"],
			["P", "P", "W", "W", "W", "W", "B", "W", "W", "W"],
			["P", "P", "W", "W", "W", "W", "B", "W", "W", "W"],
			["P", "P", "W", "W", "W", "W", "B", "W", "W", "W"],
			["P", "P", "P", "W", "W", "F", "P", "F", "F", "P"],
			["P", "P", "P", "P", "P", "P", "P", "P", "P", "P"],
			["F", "P", "P", "P", "P", "P", "P", "P", "P", "F"],
			["F", "P", "P", "P", "P", "P", "Z", "Z", "Z", "P"],
			["F", "F", "P", "P", "P", "P", "Z", "Z", "Z", "P"],
			["M", "M", "F", "P", "P", "P", "P", "P", "P", "P"],
			["M", "M", "F", "F", "F", "P", "P", "P", "P", "P"]
		],
		[
			["F", "P", "F", "F", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "F", "M", "M", "M", "M", "M"],
			["P", "P", "P", "P", "P", "P", "P", "F", "P", "P", "P", "P", "P", "P", "P", "F", "F", "M", "M", "F"],
			["P", "P", "P", "P", "F", "R", "R", "R", "R", "R", "R", "R", "R", "R", "P", "P", "P", "P", "P", "P"],
			["P", "C", "C", "C", "P", "P", "F", "M", "M", "F", "F", "P", "P", "R", "P", "P", "Z", "Z", "Z", "P"],
			["P", "C", "C", "C", "P", "M", "M", "N", "M", "M", "M", "F", "P", "R", "R", "R", "Z", "Z", "Z", "R"],
			["P", "P", "P", "P", "P", "F", "M", "M", "M", "M", "F", "P", "P", "R", "P", "P", "P", "P", "P", "P"],
			["P", "P", "P", "P", "P", "P", "F", "M", "M", "F", "P", "P", "R", "R", "F", "F", "F", "P", "P", "P"],
			["P", "F", "P", "F", "F", "R", "R", "R", "R", "R", "R", "R", "R", "F", "M", "N", "M", "F", "P", "P"],
			["F", "F", "F", "F", "F", "F", "F", "P", "P", "P", "P", "P", "F", "M", "M", "M", "M", "F", "F", "P"]
		]
	]
}